dic = {{tf= "ddənya", en= "the world"},
{tf= "ŧammua’ŧ", en= "the land"},
{tf= "šař", en= "the soil"},
{tf= "ŧaʕəžžašŧ", en= "the dust"},
{tf= "ŧaɣəbbā’ŧ", en= "the dust"},
{tf= "aƀəǧǧaʕ", en= "the mud"},
{tf= "ižđi", en= "the sand"},
{tf= "ađrā", en= "the mountain or hill"},
{tf= "ađmā", en= "the mountain or hill"},
{tf= "žžā’f", en= "the cliff or precipice"},
{tf= "addā", en= "the cliff or precipice"},
{tf= "řgəʕđəŧ", en= "the plain"},
{tf= "řəwđ’a", en= "the plain"},
{tf= "ŧizi", en= "the valley"},
{tf= "ŧayəzzāŧ", en= "the island"},
{tf= "lǧazira", en= "the island"},
{tf= "řƀā’", en= "the mainland"},
{tf= "ŧma", en= "the shore"},
{tf= "ifri", en= "the cave"},
{tf= "aman", en= "the water"},
{tf= "řəƀħā", en= "the sea"},
{tf= "ās", en= "calm"},
{tf= "hwəř", en= "rough(2)"},
{tf= "haž", en= "rough(2)"},
{tf= "kuffu", en= "the foam"},
{tf= "řəƀħā", en= "the ocean"},
{tf= "ařimam", en= "the lake"},
{tf= "ŧanda", en= "the lake"},
{tf= "řmužžəŧ", en= "the wave"},
{tf= "iɣzā", en= "the river or stream"},
{tf= "ŧasrafŧ", en= "the whirlpool"},
{tf= "ŧařa", en= "the spring or well"},
{tf= "anu", en= "the spring or well"},
{tf= "řʕuns’ā", en= "the spring or well"},
{tf= "šāšā", en= "the waterfall"},
{tf= "řɣaƀəŧ", en= "the woods or forest"},
{tf= "ddəmnəŧ", en= "the savanna"},
{tf= "ŧafřəwŧ", en= "the wood"},
{tf= "az’r’u", en= "the stone or rock"},
{tf= "zzinzal", en= "the earthquake"},
{tf= "nhəzz", en= "the earthquake"},
{tf= "ažənna", en= "the sky"},
{tf= "ŧfušŧ", en= "the sun"},
{tf= "yua", en= "the moon"},
{tf= "ŧaziri", en= "the moon"},
{tf= "iŧri", en= "the star"},
{tf= "assam", en= "the lightning"},
{tf= "řəƀr’uq", en= "the lightning"},
{tf= "ažžaž", en= "the thunder"},
{tf= "assam", en= "the bolt of lightning"},
{tf= "řəƀr’uq", en= "the bolt of lightning"},
{tf= "ŧasřiŧ n wənz’ā", en= "the rainbow"},
{tf= "ŧfawŧ", en= "the light"},
{tf= "t’t’řam", en= "the darkness"},
{tf= "ŧaǧǧəsŧ", en= "the darkness"},
{tf= "ŧiři", en= "the shade or shadow"},
{tf= "nnđa", en= "the dew"},
{tf= "lhawa", en= "the air"},
{tf= "asəmmiđ’", en= "the wind"},
{tf= "arriħ", en= "the wind"},
{tf= "asiynu", en= "the cloud"},
{tf= "ŧažnawŧ", en= "the cloud"},
{tf= "řəɣmam", en= "the cloud"},
{tf= "ŧayyuŧ", en= "the fog"},
{tf= "anz’ā", en= "the rain"},
{tf= "ađfəř", en= "the snow"},
{tf= "ažris", en= "the ice"},
{tf= "žməđ", en= "to freeze"},
{tf= "žās", en= "to freeze"},
{tf= "řħař", en= "the weather"},
{tf= "ŧiməssi", en= "the fire"},
{tf= "aħəddiq", en= "the flame"},
{tf= "ddəxxan", en= "the smoke"},
{tf= "ššyađ’", en= "the steam"},
{tf= "iɣɣəđ", en= "the ash"},
{tf= "ŧiažətt", en= "the embers"},
{tf= "ssħā’q", en= "to burn(1)"},
{tf= "ssšməđ’", en= "to burn(1)"},
{tf= "ħā’q", en= "to burn(2)"},
{tf= "šməđ’", en= "to burn(2)"},
{tf= "ssiɣ", en= "to light"},
{tf= "ssəxsi", en= "to extinguish"},
{tf= "ššʕəř", en= "the match"},
{tf= "z’alamit’", en= "the match"},
{tf= "ašəħřuf", en= "the firewood"},
{tf= "řəfħəm", en= "the charcoal"},
{tf= "řfaxā", en= "the charcoal"},
{tf= "ƀnađəm", en= "the person"},
{tf= "āyaz", en= "the man"},
{tf= "aŧarras", en= "the man"},
{tf= "ŧamɣā’ŧ", en= "the woman"},
{tf= "ŧamət’t’uŧ", en= "the woman"},
{tf= "aħənžia", en= "the boy"},
{tf= "aħr’am", en= "the boy"},
{tf= "aniyƀu", en= "the boy"},
{tf= "aħənžia", en= "the young man"},
{tf= "aħr’am", en= "the young man"},
{tf= "aʕəzri", en= "the young man"},
{tf= "ŧaħənžiaŧ", en= "the girl"},
{tf= "ŧaħr’ant", en= "the girl"},
{tf= "ŧaniyƀuŧ", en= "the girl"},
{tf= "ŧaħənžiaŧ", en= "the young woman"},
{tf= "ŧaħr’ant", en= "the young woman"},
{tf= "ŧaʕzāšŧ", en= "the young woman"},
{tf= "aħənžia", en= "the child(1)"},
{tf= "řƀəz’z’", en= "the child(1)"},
{tf= "řwašun", en= "the child(1)"},
{tf= "aħđ’iđ’", en= "the baby"},
{tf= "asiymi", en= "the baby"},
{tf= "āyaz", en= "the husband"},
{tf= "ŧamɣā’ŧ", en= "the wife"},
{tf= "mřəš", en= "to marry"},
{tf= "urā", en= "the wedding"},
{tf= "uřuf", en= "the divorce"},
{tf= "t’t’alaq", en= "the divorce"},
{tf= "ƀaƀa", en= "the father"},
{tf= "yəmma", en= "the mother"},
{tf= "lwaliđin", en= "the parents"},
{tf= "mmi", en= "the son"},
{tf= "yəǧǧi", en= "the daughter"},
{tf= "aħənžia", en= "the child(2)"},
{tf= "uma", en= "the brother"},
{tf= "uma aməqqr’an", en= "the older brother"},
{tf= "ʕzizi", en= "the older brother"},
{tf= "uma aməz’z’yan", en= "the younger brother"},
{tf= "učma", en= "the sister"},
{tf= "učma ŧaməqqr’ant", en= "the older sister"},
{tf= "učma ŧaməz’z’yant", en= "the younger sister"},
{tf= "awmaŧən", en= "the sibling"},
{tf= "ašniw", en= "the twins"},
{tf= "žəddi", en= "the grandfather"},
{tf= "awəssā", en= "the old man"},
{tf= "ħənna", en= "the grandmother"},
{tf= "ŧawəssāŧ", en= "the old woman"},
{tf= "řəžđuđ", en= "the grandparents"},
{tf= "ayyaw", en= "the grandson"},
{tf= "ŧayyawŧ", en= "the granddaughter"},
{tf= "ayyawən", en= "the grandchild"},
{tf= "xaři", en= "the mother's brother"},
{tf= "ʕzizi", en= "the father's brother"},
{tf= "xači", en= "the mother's sister"},
{tf= "ʕənti", en= "the father's sister"},
{tf= "mmis n uma", en= "the nephew"},
{tf= "ayyaw", en= "the nephew"},
{tf= "yəǧǧi-s n uma", en= "the niece"},
{tf= "ŧayyawŧ", en= "the niece"},
{tf= "mmis n xaři", en= "the cousin"},
{tf= "ŧayyawŧ", en= "the cousin"},
{tf= "mmis n ʕzizi", en= "the cousin"},
{tf= "mmis n xači", en= "the cousin"},
{tf= "yəǧǧis n xači", en= "the cousin"},
{tf= "yəǧǧis n ʕzizi", en= "the cousin"},
{tf= "ayyaw", en= "the cousin"},
{tf= "yəǧǧis n xaři", en= "the cousin"},
{tf= "řəžđuđ", en= "the ancestors"},
{tf= "ŧā’wa", en= "the descendants"},
{tf= "ađ’əggwař", en= "the father-in-law (of a man)"},
{tf= "amɣā", en= "the father-in-law (of a woman)"},
{tf= "ŧađ’əggwač", en= "the mother-in-law (of a man)"},
{tf= "lalla", en= "the mother-in-law (of a woman)"},
{tf= "iđ’əwřan", en= "the parents-in-law"},
{tf= "ađ’əggwař", en= "the son-in-law (of a man)"},
{tf= "ađ’əggwař", en= "the son-in-law (of a woman)"},
{tf= "ŧasřiŧ", en= "the daughter-in-law (of a man)"},
{tf= "ŧasřiŧ", en= "the daughter-in-law (of a woman)"},
{tf= "ađ’əggwař", en= "the sibling-in-law"},
{tf= "ařwəs", en= "the sibling-in-law"},
{tf= "ŧađ’əggwač", en= "the sibling-in-law"},
{tf= "ŧanut’", en= "the sibling-in-law"},
{tf= "ŧařwəsŧ", en= "the sibling-in-law"},
{tf= "asřif", en= "the sibling-in-law"},
{tf= "ŧasřifŧ", en= "the sibling-in-law"},
{tf= "ŧašna", en= "the stepmother"},
{tf= "āƀiƀ", en= "the stepson"},
{tf= "ŧāƀifŧ", en= "the stepdaughter"},
{tf= "ayužiř", en= "the orphan"},
{tf= "tažžač", en= "the widow"},
{tf= "ažžař", en= "the widower"},
{tf= "familya", en= "the relatives"},
{tf= "familya", en= "the family"},
{tf= "nəšš", en= "I"},
{tf= "šəkk", en= "you (singular)"},
{tf= "šəmm", en= "you (singular)"},
{tf= "nətta", en= "he"},
{tf= "nəttaŧ", en= "she"},
{tf= "nəššin", en= "we"},
{tf= "kənniw", en= "you (plural)"},
{tf= "kənnint", en= "you (plural)"},
{tf= "nihni", en= "they"},
{tf= "nihənti", en= "they"},
{tf= "lħayawan", en= "the animal"},
{tf= "awŧəm", en= "male(2)"},
{tf= "ŧawŧənt", en= "female(2)"},
{tf= "řmař", en= "the livestock"},
{tf= "aniči, ařinti", en= "the herdsman"},
{tf= "řkuri", en= "the stable or stall"},
{tf= "anwař", en= "the stable or stall"},
{tf= "afunas", en= "the bull"},
{tf= "ayənduz", en= "the bull"},
{tf= "t’ur’u", en= "the bull"},
{tf= "ayənduz", en= "the ox"},
{tf= "ŧafunasŧ", en= "the cow"},
{tf= "aʕəžmi", en= "the calf"},
{tf= "iħuřiyən", en= "the sheep"},
{tf= "išarri", en= "the ram"},
{tf= "aħuři", en= "the ram"},
{tf= "ŧixsi", en= "the ewe"},
{tf= "izmā", en= "the lamb"},
{tf= "iřəf", en= "the boar"},
{tf= "ŧiřəfŧ", en= "the sow"},
{tf= "iřəf", en= "the pig"},
{tf= "ŧɣat’t’", en= "the goat"},
{tf= "aʕəŧrus", en= "the goat"},
{tf= "amyan", en= "the he-goat"},
{tf= "iɣəyđ", en= "the kid"},
{tf= "yis", en= "the horse"},
{tf= "akiđā", en= "the horse"},
{tf= "akiđā’", en= "the stallion"},
{tf= "ŧakiđāŧ", en= "the mare"},
{tf= "řʕawđa", en= "the mare"},
{tf= "afā’xan", en= "the foal or colt"},
{tf= "ažʕuđ", en= "the foal or colt"},
{tf= "aɣyuř", en= "the donkey"},
{tf= "asāđun", en= "the mule"},
{tf= "yaz’iđ’", en= "the cock/rooster"},
{tf= "ŧyaz’it’", en= "the hen"},
{tf= "ŧyaz’it’", en= "the chicken"},
{tf= "aƀākiw", en= "the goose"},
{tf= "ŧyaz’it’ n waman", en= "the duck"},
{tf= "ŧpaƀut", en= "the duck"},
{tf= "řʕušš", en= "the nest"},
{tf= "ažđ’iđ’", en= "the bird"},
{tf= "ɣaƀyut’a", en= "the seagull"},
{tf= "fāšu", en= "the eagle"},
{tf= "ažiđā", en= "the eagle"},
{tf= "ŧmadda", en= "the eagle"},
{tf= "řƀaz", en= "the hawk"},
{tf= "asiwan", en= "the hawk"},
{tf= "řwəđ’wađ’", en= "the bat"},
{tf= "ƀaƀaɣayyu", en= "the parrot"},
{tf= "ƀaɣəř", en= "the crow"},
{tf= "ađƀia", en= "the dove"},
{tf= "muka", en= "the owl"},
{tf= "ayđi", en= "the dog"},
{tf= "aqzin", en= "the dog"},
{tf= "ahəggā", en= "the dog"},
{tf= "aqninni", en= "the rabbit"},
{tf= "muš’š’", en= "the cat"},
{tf= "aɣāđa", en= "the mouse or rat"},
{tf= "t’uppa", en= "the mouse or rat"},
{tf= "asřəm", en= "the fish"},
{tf= "aqšua", en= "the scale"},
{tf= "aʕƀan", en= "the scale"},
{tf= "iməžžāžā", en= "the gill"},
{tf= "ažɣuř", en= "the shell"},
{tf= "řqiřš", en= "the shark"},
{tf= "ddənfiř", en= "the porpoise or dolphin"},
{tf= "ƀayana", en= "the whale"},
{tf= "ŧazřənt", en= "the freshwater eel"},
{tf= "uššən", en= "the wolf"},
{tf= "ayrađ", en= "the lion"},
{tf= "ddubb", en= "the bear"},
{tf= "išʕəƀ", en= "the fox"},
{tf= "řqāđ", en= "the monkey"},
{tf= "lfil", en= "the elephant"},
{tf= "ařɣəm", en= "the camel"},
{tf= "aƀəʕʕuš", en= "the insect"},
{tf= "ŧiššəšŧ", en= "the head louse"},
{tf= "infā", en= "the body louse"},
{tf= "iwət’t’đ’ən", en= "the nit"},
{tf= "šuađu", en= "the flea"},
{tf= "ŧamšət’t’ n yiɣəss", en= "the centipede"},
{tf= "ŧɣāđənt", en= "the scorpion"},
{tf= "sr’aqəzzit", en= "the cockroach"},
{tf= "ŧikəđ’fət’", en= "the ant"},
{tf= "nnməř", en= "the ant"},
{tf= "qundʕa", en= "the spider"},
{tf= "ƀunif", en= "the spider"},
{tf= "arrŧiřa", en= "the spider"},
{tf= "axmā’", en= "the spider web"},
{tf= "ŧizizwa", en= "the bee"},
{tf= "ŧaɣr’as’ŧ", en= "the beehive"},
{tf= "iaz’z’a", en= "the wasp"},
{tf= "izi", en= "the fly"},
{tf= "ŧiziŧ", en= "the sandfly or midge or gnat"},
{tf= "nnamus", en= "the mosquito"},
{tf= "ɣamba", en= "the prawns or shrimp"},
{tf= "ŧikəđ’fət’ ŧaruməšŧ", en= "the termites"},
{tf= "ađan n tmuaŧ", en= "the worm"},
{tf= "fiɣā’", en= "the snake"},
{tf= "ŧařəfsa", en= "the snake"},
{tf= "ƀusəkka", en= "the snake"},
{tf= "ayāz’iz’", en= "the hare"},
{tf= "ŧižāšřəšŧ", en= "the quail"},
{tf= "kangaru", en= "the kangaroo"},
{tf= "ŧaŧa", en= "the chameleon"},
{tf= "afāt’t’u", en= "the butterfly"},
{tf= "ŧaħžižat", en= "the butterfly"},
{tf= "ŧmua’ɣi", en= "the grasshopper"},
{tf= "bua’xs", en= "the grasshopper"},
{tf= "ƀuššəř", en= "the snail"},
{tf= "aɣřař", en= "the snail"},
{tf= "ŧqā’qr’a", en= "the frog"},
{tf= "aħāmšā", en= "the lizard"},
{tf= "ŧazəřmumməšŧ", en= "the lizard"},
{tf= "ttimsaħ", en= "the crocodile or alligator"},
{tf= "išfā", en= "the turtle"},
{tf= "arriməŧ", en= "the body"},
{tf= "ddat", en= "the body"},
{tf= "ŧiřməšŧ", en= "the skin or hide"},
{tf= "açsum", en= "the flesh"},
{tf= "ašəwwaf", en= "the hair"},
{tf= "z’ət’t’u", en= "the hair"},
{tf= "aʕəšmia", en= "the beard"},
{tf= "ŧmāŧ", en= "the beard"},
{tf= "ššʕā", en= "the body hair"},
{tf= "izaggwən", en= "the pubic hair"},
{tf= "ŧaqšuaŧ", en= "the dandruff"},
{tf= "iđammən", en= "the blood"},
{tf= "az’wā", en= "the vein or artery"},
{tf= "iɣəss", en= "the bone"},
{tf= "ŧaɣəzđisŧ", en= "the rib"},
{tf= "išš", en= "the horn"},
{tf= "ŧanəwwāŧ", en= "the tail"},
{tf= "ŧaz’ənt’it’", en= "the tail"},
{tf= "akənnas", en= "the tail"},
{tf= "aʕrua n tit’t’", en= "the back"},
{tf= "ssənsřəŧ", en= "the spine"},
{tf= "azəǧǧif", en= "the head"},
{tf= "aqəyyua", en= "the head"},
{tf= "ŧaqəšqašŧ", en= "the skull"},
{tf= "aǧǧi", en= "the brain"},
{tf= "aməřɣiɣ", en= "the brain"},
{tf= "řmuxx", en= "the brain"},
{tf= "uđəm", en= "the face"},
{tf= "aɣəmbuƀ", en= "the face"},
{tf= "aɣənzua", en= "the face"},
{tf= "s’s’ifəŧ", en= "the face"},
{tf= "ŧanyiaŧ", en= "the forehead"},
{tf= "aɣəsmia", en= "the jaw"},
{tf= "agəmmiz", en= "the cheek"},
{tf= "ŧaɣəsmiaŧ", en= "the chin"},
{tf= "ŧit’t’", en= "the eye"},
{tf= "ŧimmi", en= "the eyebrow"},
{tf= "aʕrua n tit’t’", en= "the eyelid"},
{tf= "aƀəř", en= "the eyelash"},
{tf= "ɣməz", en= "to blink"},
{tf= "aməz’z’uɣ", en= "the ear"},
{tf= "aməžžun", en= "the ear"},
{tf= "ŧaħr’us’ŧ", en= "the earlobe"},
{tf= "ŧinzā", en= "the nose"},
{tf= "ŧinzā", en= "the nostril"},
{tf= "aqənnin", en= "the nasal mucus"},
{tf= "axřuř", en= "the nasal mucus"},
{tf= "aqəmmum", en= "the mouth"},
{tf= "ašənquƀ", en= "the beak"},
{tf= "ayənšiš", en= "the lip"},
{tf= "anfif", en= "the lip"},
{tf= "iřəs", en= "the tongue"},
{tf= "ŧiɣməsŧ", en= "the tooth"},
{tf= "anəɣ", en= "the gums"},
{tf= "ŧasiaŧ", en= "the molar tooth"},
{tf= "iri", en= "the neck"},
{tf= "ižiman", en= "the nape of the neck"},
{tf= "ŧmižža", en= "the throat"},
{tf= "ŧaɣrut’t’", en= "the shoulder"},
{tf= "iɣaǧǧən", en= "the shoulderblade"},
{tf= "ɣiř", en= "the arm"},
{tf= "fus", en= "the arm"},
{tf= "ŧaddəxŧ", en= "the armpit"},
{tf= "ŧaɣmā’ŧ", en= "the elbow"},
{tf= "fus", en= "the hand"},
{tf= "ŧařəqqa", en= "the palm of the hand"},
{tf= "ŧisi", en= "the palm of the hand"},
{tf= "đ’ađ’", en= "the finger"},
{tf= "iməz", en= "the thumb"},
{tf= "iššā", en= "the fingernail"},
{tf= "đ’ā", en= "the leg"},
{tf= "ifaddən", en= "the thigh"},
{tf= "ŧar’r’əmmant", en= "the calf of the leg"},
{tf= "fuđ", en= "the knee"},
{tf= "đ’ā", en= "the foot"},
{tf= "ŧašʕəfŧ", en= "the ankle"},
{tf= "niaz", en= "the heel"},
{tf= "řimāŧ", en= "the footprint"},
{tf= "ŧifđənt", en= "the toe"},
{tf= "afriw", en= "the wing"},
{tf= "arriš", en= "the feather"},
{tf= "afā", en= "the feather"},
{tf= "iđmān", en= "the chest"},
{tf= "žžuf", en= "the chest"},
{tf= "ibbəš", en= "the breast"},
{tf= "ŧinɣi", en= "the udder"},
{tf= "ŧaʕəbbut’", en= "the navel"},
{tf= "aʕəddis", en= "the belly"},
{tf= "uř", en= "the heart"},
{tf= "ŧar’uŧ", en= "the lung"},
{tf= "ŧsa", en= "the liver"},
{tf= "ŧiz’z’əč", en= "the kidney"},
{tf= "ināfəđ’", en= "the spleen"},
{tf= "st’umaɣu", en= "the stomach"},
{tf= "lmaʕədda", en= "the stomach"},
{tf= "ađan", en= "the intestines or guts"},
{tf= "ƀururu", en= "the intestines or guts"},
{tf= "ŧaʕəddisŧ", en= "the waist"},
{tf= "ŧaməssat’t’", en= "the hip"},
{tf= "ŧadiyniŧ", en= "the buttocks"},
{tf= "ažəʕƀuƀ", en= "the buttocks"},
{tf= "qunniđ’", en= "the buttocks"},
{tf= "žuffiđ’", en= "the buttocks"},
{tf= "az’wā", en= "the sinew or tendon"},
{tf= "lwəlda", en= "the womb"},
{tf= "řəmruraŧ", en= "the womb"},
{tf= "iməǧǧařən", en= "the testicles"},
{tf= "ŧiqəllalin", en= "the testicles"},
{tf= "aqəǧǧař", en= "the testicles"},
{tf= "aƀřuř", en= "the penis"},
{tf= "amənyā", en= "the penis"},
{tf= "aqəllaw", en= "the penis"},
{tf= "aƀəššun", en= "the vagina"},
{tf= "aħəššun", en= "the vagina"},
{tf= "ŧaqənzisŧ", en= "the vulva"},
{tf= "inšišən", en= "the vulva"},
{tf= "arr nnəfs", en= "to breathe"},
{tf= "nndfa", en= "to yawn"},
{tf= "ŧiɣɣəs’ŧ", en= "to hiccough"},
{tf= "usu", en= "to cough"},
{tf= "ʕđ’əs", en= "to sneeze"},
{tf= "ns’əđ’", en= "to sneeze"},
{tf= "ddəđ", en= "to perspire"},
{tf= "ssusəf", en= "to spit"},
{tf= "ʕuqq", en= "to vomit"},
{tf= "arr", en= "to vomit"},
{tf= "ns’əř", en= "to vomit"},
{tf= "zʕəf", en= "to bite"},
{tf= "mmā’məš", en= "to bite"},
{tf= "řsəħ", en= "to lick"},
{tf= "sřiyzəz", en= "to dribble"},
{tf= "sřuddi", en= "to dribble"},
{tf= "t’t’əs", en= "to sleep"},
{tf= "šxā’", en= "to snore"},
{tf= "ššuxřəđ’", en= "to snore"},
{tf= "uaža", en= "to dream"},
{tf= "faq", en= "to wake up"},
{tf= "z’āđ’", en= "to fart"},
{tf= "kəff", en= "to fart"},
{tf= "ƀəšš", en= "to piss"},
{tf= "ƀāđ’", en= "to shit"},
{tf= "qqu", en= "to have sex"},
{tf= "fħəř", en= "to have sex"},
{tf= "āžiž", en= "to shiver"},
{tf= "ssiađ", en= "to bathe"},
{tf= "ar’u", en= "to beget"},
{tf= "xřəq", en= "to be born"},
{tf= "ŧəçsi aʕəddis", en= "pregnant"},
{tf= "ŧəçsi aʕəddis", en= "to conceive"},
{tf= "ddā", en= "to be alive"},
{tf= "ŧuđāŧ", en= "the life"},
{tf= "lħayat", en= "the life"},
{tf= "mməŧ", en= "to die"},
{tf= "nnur’i", en= "to die"},
{tf= "aməttin", en= "dead"},
{tf= "řməyyəŧ", en= "dead"},
{tf= "ɣā’q", en= "to drown"},
{tf= "šš", en= "to drown"},
{tf= "nəɣ", en= "to kill"},
{tf= "řxəšƀəŧ", en= "the corpse"},
{tf= "amuađ’us", en= "the carcass"},
{tf= "nd’əř", en= "to bury"},
{tf= "and’əř", en= "the grave"},
{tf= "žhəđ", en= "strong"},
{tf= "qwa", en= "strong"},
{tf= "đ’ʕəf", en= "weak"},
{tf= "qđ’a", en= "weak"},
{tf= "s’əħħ", en= "healthy"},
{tf= "ssħuss", en= "sick/ill"},
{tf= "hřəš", en= "sick/ill"},
{tf= "ŧiməssi", en= "the fever"},
{tf= "asəmmiđ’", en= "the cold"},
{tf= "řəhřaš", en= "the disease"},
{tf= "ayəzzim", en= "the wound or sore"},
{tf= "t’t’aƀəš", en= "the bruise"},
{tf= "ŧuffət", en= "the swelling"},
{tf= "ašmaz", en= "the itch"},
{tf= "šməz", en= "to scratch"},
{tf= "ŧāffixŧ", en= "the blister"},
{tf= "axənza", en= "the boil"},
{tf= "řgiħħ", en= "the pus"},
{tf= "t’t’aƀəʕ", en= "the scar"},
{tf= "ssgənfa", en= "to cure"},
{tf= "ađ’ƀiƀ", en= "the physician"},
{tf= "ddwa", en= "the medicine"},
{tf= "ssəmm", en= "the poison"},
{tf= "arrhaž", en= "the poison"},
{tf= "aħəř", en= "tired"},
{tf= "āyyəħ", en= "to rest"},
{tf= "zzyənfa", en= "to rest"},
{tf= "ʕgəz", en= "lazy"},
{tf= "aqəššā", en= "bald"},
{tf= "qarrəm", en= "lame"},
{tf= "ađəhšua", en= "deaf"},
{tf= "ađ’āđua", en= "deaf"},
{tf= "aynaw", en= "mute"},
{tf= "az’iz’un", en= "mute"},
{tf= "ađ’āɣař", en= "blind"},
{tf= "s’šā", en= "drunk"},
{tf= "ɣəlla", en= "drunk"},
{tf= "aʕāyan", en= "naked"},
{tf= "šš", en= "to eat"},
{tf= "mašša", en= "the food"},
{tf= "lmakla", en= "the food"},
{tf= "əŋw", en= "cooked"},
{tf= "aziyza", en= "raw"},
{tf= "əŋw", en= "ripe"},
{tf= "xs’ā", en= "rotten"},
{tf= "su", en= "to drink"},
{tf= "ħřu", en= "to drink"},
{tf= "ǧǧaz’", en= "to be hungry"},
{tf= "ƀuhəyyuf", en= "the famine"},
{tf= "ffađ", en= "to be thirsty"},
{tf= "t’t’əđ’", en= "to suck"},
{tf= "z’əmm", en= "to suck"},
{tf= "fəz’z’", en= "to chew"},
{tf= "s’s’əɣři", en= "to swallow"},
{tf= "žəyyəf", en= "to choke"},
{tf= "ssəŋw", en= "to cook"},
{tf= "ŧāŧā", en= "to boil"},
{tf= "šnəf", en= "to roast or fry"},
{tf= "šwa", en= "to roast or fry"},
{tf= "qřa", en= "to roast or fry"},
{tf= "āf", en= "to roast or fry"},
{tf= "ggw", en= "to bake"},
{tf= "afarran", en= "the oven"},
{tf= "ŧafqunt", en= "the oven"},
{tf= "māmit’a", en= "the pot"},
{tf= "ŧasəçsuŧ", en= "the pot"},
{tf= "ŧaɣəllašŧ", en= "the kettle"},
{tf= "aməqraž", en= "the kettle"},
{tf= "řmaqřa", en= "the pan"},
{tf= "řƀuaməŧ", en= "the pan"},
{tf= "t’t’əƀs’i", en= "the dish"},
{tf= "ŧaz’əwđa", en= "the dish"},
{tf= "t’t’əƀs’i", en= "the plate"},
{tf= "afənžař", en= "the bowl"},
{tf= "aqƀuš", en= "the bowl"},
{tf= "aɣarraf", en= "the jug/pitcher"},
{tf= "ŧaƀriqŧ", en= "the jug/pitcher"},
{tf= "ŧkuppat", en= "the cup"},
{tf= "ŧat’əƀsəšŧ", en= "the saucer"},
{tf= "ŧaɣənžašŧ", en= "the spoon"},
{tf= "řmus", en= "the knife(1)"},
{tf= "fuřšit’a", en= "the fork"},
{tf= "ǧǧəqqađ’", en= "the tongs"},
{tf= "mašša", en= "the meal"},
{tf= "lmakla", en= "the meal"},
{tf= "āyyəq", en= "the breakfast"},
{tf= "aməšři", en= "the lunch"},
{tf= "řəfđ’ua", en= "the lunch"},
{tf= "amənsi", en= "the supper"},
{tf= "qəššā’", en= "to peel"},
{tf= "ssif", en= "to sieve or to strain"},
{tf= "ɣā’ƀəř", en= "to sieve or to strain"},
{tf= "nžā’", en= "to scrape"},
{tf= "ħarrəš", en= "to stir or to mix"},
{tf= "aɣrum", en= "the bread"},
{tf= "āšŧi", en= "the dough"},
{tf= "ggw", en= "to knead"},
{tf= "ān", en= "the flour"},
{tf= "ħāy", en= "to crush or to grind"},
{tf= "ŧasiaŧ", en= "the mill"},
{tf= "iđiyđi", en= "the mortar(1)"},
{tf= "řƀua’qi", en= "the mortar(1)"},
{tf= "azđuz", en= "the pestle"},
{tf= "açsum", en= "the meat"},
{tf= "s’us’iŧ", en= "the sausage"},
{tf= "ŧaħriaŧ", en= "the soup"},
{tf= "s’uppa", en= "the soup"},
{tf= "řxuđ’āŧ", en= "the vegetables"},
{tf= "ƀaw", en= "the bean"},
{tf= "ŧƀat’at’att", en= "the potato"},
{tf= "řxuđ’āŧ", en= "the fruit"},
{tf= "ŧazāŧ", en= "the fig"},
{tf= "qurrəʕ", en= "the fig"},
{tf= "ađ’iř", en= "the grape"},
{tf= "zzƀiƀ", en= "the grape"},
{tf= "aɣyay", en= "the nut"},
{tf= "ŧaɣyašŧ", en= "the nut"},
{tf= "ŧazitunt", en= "the olive"},
{tf= "zzəšŧ", en= "the oil"},
{tf= "ŧađunt", en= "the grease or fat"},
{tf= "ŧaməǧǧaħŧ", en= "the salt"},
{tf= "řfəřfəř", en= "the pepper"},
{tf= "řfəřfəř itəqqsən", en= "the chili pepper"},
{tf= "ŧammənt", en= "the honey"},
{tf= "ssəkwā", en= "the sugar"},
{tf= "aɣi", en= "the milk"},
{tf= "aɣi asəmmam", en= "the milk"},
{tf= "ađɣəs", en= "the milk"},
{tf= "z’z’i", en= "to milk"},
{tf= "kisu", en= "the cheese"},
{tf= "ddhən", en= "the butter"},
{tf= "ŧřussi", en= "the butter"},
{tf= "məšruƀat’", en= "the drink"},
{tf= "ƀinu", en= "the wine"},
{tf= "aman", en= "the wine"},
{tf= "sařƀisa", en= "the beer"},
{tf= "ƀirra", en= "the beer"},
{tf= "ššr’aƀ", en= "the fermented drink"},
{tf= "ŧaməǧǧač", en= "the egg"},
{tf= "řmāħ", en= "the yolk"},
{tf= "iađ’", en= "to put on"},
{tf= "ar’r’uđ’", en= "the clothing or clothes"},
{tf= "axəyyađ’", en= "the tailor"},
{tf= "řkəttan", en= "the cloth"},
{tf= "ŧađ’ufŧ", en= "the wool"},
{tf= "řəqt’ən", en= "the cotton"},
{tf= "řəħria", en= "the silk"},
{tf= "asřix", en= "the fur"},
{tf= "ššāk", en= "the leather"},
{tf= "ǧǧəm", en= "to spin"},
{tf= "đarrəz", en= "to weave"},
{tf= "řmāməŧ", en= "the loom"},
{tf= "xəyyəđ’", en= "to sew"},
{tf= "isiyni", en= "the needle(1)"},
{tf= "ŧisiynəfŧ", en= "the needle(1)"},
{tf= "fiřu", en= "the thread"},
{tf= "asəřham", en= "the cloak"},
{tf= "ħāš", en= "the cloak"},
{tf= "ddfin", en= "the (woman's) dress"},
{tf= "akəbbuđ’", en= "the coat"},
{tf= "ŧaqmižžat", en= "the shirt"},
{tf= "iri", en= "the collar"},
{tf= "iməžžan n təqmižaŧ", en= "the collar"},
{tf= "fařd’a", en= "the skirt"},
{tf= "ssāwař", en= "the trousers"},
{tf= "ttqašia", en= "the sock or stocking"},
{tf= "ŧsiřit", en= "the shoe"},
{tf= "ahākus", en= "the shoe"},
{tf= "ssand’aliya", en= "the shoe"},
{tf= "čanklaŧ", en= "the shoe"},
{tf= "řƀut’", en= "the boot"},
{tf= "ađ’arraf", en= "the shoemaker"},
{tf= "ŧšaššəšŧ", en= "the hat or cap"},
{tf= "šap’p’u", en= "the hat or cap"},
{tf= "t’t’āƀuš", en= "the hat or cap"},
{tf= "ŧaħəzzant", en= "the belt"},
{tf= "ŧaƀyasŧ", en= "the belt"},
{tf= "want’is’", en= "the glove"},
{tf= "lltam", en= "the veil"},
{tf= "žžib", en= "the pocket"},
{tf= "řəqfař", en= "the button"},
{tf= "ŧisiynəfŧ", en= "the pin"},
{tf= "āqqəm", en= "the ornament or adornment"},
{tf= "ŧxađənt", en= "the ring"},
{tf= "ŧaməqyasŧ", en= "the bracelet"},
{tf= "ŧasəddəšŧ", en= "the necklace"},
{tf= "ŧađmant", en= "the bead"},
{tf= "ŧaxras’ŧ", en= "the earring"},
{tf= "ŧasəƀnəšŧ", en= "the headband or headdress"},
{tf= "ŧiggəsŧ", en= "the tattoo"},
{tf= "řəmħiaməŧ", en= "the handkerchief or rag"},
{tf= "řfut’a", en= "the towel"},
{tf= "ŧamšət’t’", en= "the comb"},
{tf= "ŧamšət’t’", en= "the brush"},
{tf= "mmuđ", en= "the plait/braid"},
{tf= "qučiya", en= "the razor"},
{tf= "fumađ’a", en= "the ointment"},
{tf= "s’s’aƀun", en= "the soap"},
{tf= "ŧisiŧ", en= "the mirror"},
{tf= "zđəɣ", en= "to live"},
{tf= "ŧaddāŧ", en= "the house"},
{tf= "ŧanwač", en= "the hut"},
{tf= "čaƀul’a", en= "the garden-house"},
{tf= "ŧaqiđ’unt", en= "the tent"},
{tf= "ŧʕiššəwŧ", en= "the tent"},
{tf= "řəmraħ", en= "the yard or court"},
{tf= "ŧiɣā’ɣā’ŧ", en= "the cookhouse"},
{tf= "řƀiŧ", en= "the room"},
{tf= "ŧɣua’fəŧ", en= "the room"},
{tf= "axxam", en= "the room"},
{tf= "ŧawwāŧ", en= "the door or gate"},
{tf= "akwađrun", en= "the doorpost"},
{tf= "zzəkrun", en= "the lock"},
{tf= "qandaw", en= "the latch or door-bolt"},
{tf= "ŧišfāŧ", en= "the padlock"},
{tf= "řməftaħ", en= "the key"},
{tf= "řkazi", en= "the window"},
{tf= "ŧƀuažət", en= "the window"},
{tf= "ŧammua’ŧ", en= "the floor"},
{tf= "řħiđ’", en= "the wall"},
{tf= "ŧiɣā’ɣā’ŧ", en= "the fireplace"},
{tf= "šalimu", en= "the chimney"},
{tf= "ssəǧǧum", en= "the ladder"},
{tf= "řəšŧu", en= "the bed"},
{tf= "qama", en= "the bed"},
{tf= "ŧsunta", en= "the pillow"},
{tf= "malt’a", en= "the blanket"},
{tf= "řkuasi", en= "the chair"},
{tf= "missa", en= "the table"},
{tf= "řqəndiř", en= "the lamp or torch"},
{tf= "asfəđ’", en= "the lamp or torch"},
{tf= "tyāna", en= "the lamp or torch"},
{tf= "lamb’a", en= "the lamp or torch"},
{tf= "ŧšumʕətt", en= "the candle"},
{tf= "řmā’fəʕ", en= "the shelf"},
{tf= "řməđwəđ", en= "the trough"},
{tf= "asqif", en= "the roof"},
{tf= "ŧaz’əqqa", en= "the roof"},
{tf= "ŧaħnašŧ", en= "the beam"},
{tf= "apilā", en= "the post or pole"},
{tf= "ŧafřəwŧ", en= "the board"},
{tf= "řqəws", en= "the arch"},
{tf= "aƀənnay", en= "the mason"},
{tf= "ŧlažua’ŧ", en= "the brick"},
{tf= "ƀurrəs ?", en= "the mortar(2)"},
{tf= "šař", en= "the adobe"},
{tf= "řəʕzib", en= "the camp"},
{tf= "ašrag", en= "to tan"},
{tf= "afəǧǧaħ", en= "the farmer"},
{tf= "iyyā", en= "the field"},
{tf= "ŧaƀħiaŧ", en= "the garden"},
{tf= "řʕās’ŧ", en= "the garden"},
{tf= "žžařđ’a", en= "the garden"},
{tf= "ssəɣmi", en= "to cultivate"},
{tf= "afray", en= "the fence"},
{tf= "aqwia", en= "the fence"},
{tf= "aħfua", en= "the ditch"},
{tf= "axƀuš", en= "the ditch"},
{tf= "ŧāya", en= "the ditch"},
{tf= "řməqs’ā", en= "the ditch"},
{tf= "šāz", en= "to plough/plow"},
{tf= "ɣəz", en= "to dig"},
{tf= "ħfā", en= "to dig"},
{tf= "ŧs’appa", en= "the spade"},
{tf= "lƀal’a", en= "the shovel"},
{tf= "ařiyzim", en= "the hoe"},
{tf= "ŧqaƀut", en= "the hoe"},
{tf= "ŧazzāŧ", en= "the fork(2)/pitchfork"},
{tf= "ŧazzāŧ", en= "the rake"},
{tf= "zāʕ", en= "to sow"},
{tf= "řħəbb", en= "the seed"},
{tf= "mžā", en= "to mow"},
{tf= "amžā", en= "the sickle or scythe"},
{tf= "ssā’wəŧ", en= "to thresh"},
{tf= "and’rā", en= "the threshing-floor"},
{tf= "řɣiǧǧəŧ", en= "the harvest"},
{tf= "iađən", en= "the wheat"},
{tf= "iməndi", en= "the barley"},
{tf= "d’d’ra", en= "the maize/corn"},
{tf= "ar’r’uz’", en= "the rice"},
{tf= "arrƀiʕ", en= "the grass"},
{tf= "řum", en= "the hay"},
{tf= "nnəwwā", en= "the plant"},
{tf= "z’z’u", en= "to plant"},
{tf= "az’wā", en= "the root"},
{tf= "řfāʕ", en= "the branch"},
{tf= "fiŧu", en= "the branch"},
{tf= "ŧas’ət’t’a", en= "the branch"},
{tf= "ŧawr’iqŧ", en= "the leaf"},
{tf= "ŧifāšŧ", en= "the leaf"},
{tf= "ŧanəwwašŧ", en= "the flower"},
{tf= "ssəžžāŧ", en= "the tree"},
{tf= "ŧayđa", en= "the pine"},
{tf= "řƀəǧǧuđ’", en= "the acorn"},
{tf= "ŧz’ayāŧ", en= "the vine"},
{tf= "t’t’aƀa", en= "the tobacco"},
{tf= "kəyyəf", en= "to smoke"},
{tf= "kəmm", en= "to smoke"},
{tf= "ssəƀsi", en= "the pipe"},
{tf= "ŧiyyāŧ", en= "the tree stump"},
{tf= "aɣr’us", en= "the tree trunk"},
{tf= "ŧfuaçəŧ ?", en= "the forked branch"},
{tf= "asəřɣaɣ", en= "the sap"},
{tf= "ŧiz’đ’ənt", en= "the palm tree"},
{tf= "ŧiyni", en= "the palm tree"},
{tf= "kuku", en= "the coconut"},
{tf= "llaymun", en= "the citrus fruit"},
{tf= "lləššin", en= "the citrus fruit"},
{tf= "mandarina", en= "the citrus fruit"},
{tf= "plat’anu", en= "the banana"},
{tf= "lƀanan", en= "the banana"},
{tf= "ŧaxsašŧ", en= "the pumpkin or squash"},
{tf= "ɣanim", en= "the bamboo"},
{tf= "ŧayzint", en= "the nettle"},
{tf= "aɣrum n tƀaɣřa", en= "the mushroom"},
{tf= "asənnan", en= "the needle(2)"},
{tf= "ŧayđa", en= "the cone"},
{tf= "gg", en= "to do"},
{tf= "gg", en= "to make"},
{tf= "řxəđməŧ", en= "the work"},
{tf= "ssfā’ɣ", en= "to bend"},
{tf= "đ’fəs’", en= "to fold"},
{tf= "qqən", en= "to tie"},
{tf= "šədd", en= "to tie"},
{tf= "šāf", en= "to tie"},
{tf= "ā’xu", en= "to untie"},
{tf= "ssənsřəŧ", en= "the chain"},
{tf= "iǧǧi", en= "the rope"},
{tf= "ŧamriaŧ", en= "the rope"},
{tf= "asɣun", en= "the rope"},
{tf= "ašəddi", en= "the knot"},
{tf= "wwəŧ", en= "to strike or hit or beat"},
{tf= "ssqəř", en= "to strike or hit or beat"},
{tf= "qqəs", en= "to cut"},
{tf= "fři", en= "to cut"},
{tf= "qqəs", en= "to cut down"},
{tf= "fəǧǧəq", en= "to chop"},
{tf= "fās", en= "to chop"},
{tf= "zđəm", en= "to chop"},
{tf= "pikā", en= "to stab"},
{tf= "qqəs", en= "to stab"},
{tf= "wwəŧ s řmus", en= "to stab"},
{tf= "řmus", en= "the knife(2)"},
{tf= "ŧaxəđməšŧ", en= "the knife(2)"},
{tf= "ŧiməšr’ađ’", en= "the scissors or shears"},
{tf= "ŧiɣəndin", en= "the scissors or shears"},
{tf= "řəmqəss", en= "the scissors or shears"},
{tf= "ššaqua’", en= "the axe/ax"},
{tf= "āz’", en= "to break"},
{tf= "arrəz’", en= "broken"},
{tf= "ƀđ’a", en= "to split"},
{tf= "ɣā’s", en= "to tear"},
{tf= "qqās", en= "to tear"},
{tf= "šarrəg", en= "to tear"},
{tf= "azu", en= "to skin"},
{tf= "sřəx", en= "to skin"},
{tf= "ħəkk", en= "to rub"},
{tf= "nħəđ", en= "to rub"},
{tf= "msəħ", en= "to wipe"},
{tf= "sarrəħ", en= "to stretch"},
{tf= "žƀəđ", en= "to pull"},
{tf= "žar’r’", en= "to pull"},
{tf= "ssu", en= "to spread out"},
{tf= "ā’šəg", en= "to hang up"},
{tf= "ayəř", en= "to hang up"},
{tf= "ʕəbbəz’", en= "to press"},
{tf= "bbəz’", en= "to press"},
{tf= "z’əmm", en= "to squeeze"},
{tf= "far’r’əɣ", en= "to pour"},
{tf= "nɣəř", en= "to pour"},
{tf= "kəbb", en= "to pour"},
{tf= "ssiađ", en= "to wash"},
{tf= "ssřiř", en= "to wash"},
{tf= "s’əbbən", en= "to wash"},
{tf= "fāđ’", en= "to sweep"},
{tf= "ŧaməđwasŧ", en= "the broom"},
{tf= "anəžžā", en= "the carpenter"},
{tf= "ƀna", en= "to build"},
{tf= "barrəm", en= "to bore"},
{tf= "řmənšā’", en= "the saw"},
{tf= "afđ’is", en= "the hammer"},
{tf= "řməs’s’əŧ", en= "the hammer"},
{tf= "aməsmia", en= "the nail"},
{tf= "ǧǧəssəq", en= "the glue"},
{tf= "amziř", en= "the blacksmith"},
{tf= "gg řqařəƀ", en= "to forge"},
{tf= "uaɣ", en= "the gold"},
{tf= "nnuqā’ŧ", en= "the silver"},
{tf= "nnħas", en= "the copper"},
{tf= "uzzař", en= "the iron"},
{tf= "řəxfif", en= "the lead"},
{tf= "aqədduħ", en= "the tin or tinplate"},
{tf= "aqəddā", en= "the potter"},
{tf= "s’ənnəʕ", en= "to mould/mold"},
{tf= "ŧřixŧ", en= "the clay"},
{tf= "zzaž", en= "the glass"},
{tf= "mmuđ", en= "to weave or plait/braid"},
{tf= "ŧazyawŧ", en= "the basket"},
{tf= "aqƀuƀ", en= "the basket"},
{tf= "ažāŧiř", en= "the mat"},
{tf= "ŧaz’āƀəšŧ", en= "the rug"},
{tf= "t’appit’", en= "the rug"},
{tf= "ŧaħarrafŧ", en= "the fan"},
{tf= "ħarrəƀ", en= "to fan"},
{tf= "ɣəz", en= "to carve"},
{tf= "ŧřima", en= "the chisel"},
{tf= "pintura", en= "the paint"},
{tf= "ssƀaɣa", en= "the paint"},
{tf= "pintā", en= "to paint"},
{tf= "ayəm", en= "to draw water"},
{tf= "žiž", en= "the peg"},
{tf= "ŧřima", en= "the whetstone"},
{tf= "smutti", en= "to move"},
{tf= "qřəƀ", en= "to turn"},
{tf= "nnəqřəƀ", en= "to turn around"},
{tf= "šməs", en= "to wrap"},
{tf= "ssəqnunni", en= "to roll"},
{tf= "ssəħnunnəđ’", en= "to roll"},
{tf= "ɣđ’əř", en= "to drop"},
{tf= "zeyyā", en= "to twist"},
{tf= "kkā", en= "to rise"},
{tf= "ā’fəʕ", en= "to raise or lift"},
{tf= "ssgəʕʕəđ", en= "to raise or lift"},
{tf= "wđ’a", en= "to fall"},
{tf= "uđum", en= "to drip"},
{tf= "nd’ā", en= "to throw"},
{tf= "səyyəƀ", en= "to throw"},
{tf= "ħri", en= "to throw"},
{tf= "řqa", en= "to catch"},
{tf= "zzəřz", en= "to shake"},
{tf= "azzəř", en= "to flow"},
{tf= "ɣđ’əs", en= "to sink"},
{tf= "fđəħ", en= "to float"},
{tf= "ʕum", en= "to swim"},
{tf= "fđəħ", en= "to swim"},
{tf= "ɣut’t’is’", en= "to dive"},
{tf= "r’ušš", en= "to splash"},
{tf= "đ’u", en= "to fly"},
{tf= "fāfā", en= "to fly"},
{tf= "ssuđ’", en= "to blow"},
{tf= "mmuađ", en= "to crawl"},
{tf= "qān ifaddən", en= "to kneel"},
{tf= "ƀāš", en= "to kneel"},
{tf= "qiddu", en= "to crouch"},
{tf= "ħřuǧǧəđ", en= "to slide or slip"},
{tf= "ħřuttəf", en= "to slide or slip"},
{tf= "nd’u", en= "to jump"},
{tf= "ngəz", en= "to jump"},
{tf= "āšəř", en= "to kick"},
{tf= "t’iřu", en= "to kick"},
{tf= "šđ’əħ", en= "to dance"},
{tf= "uyua", en= "to walk"},
{tf= "zəħħəf", en= "to limp"},
{tf= "qəžđəħ", en= "to limp"},
{tf= "azzəř", en= "to run"},
{tf= "ruħ", en= "to go"},
{tf= "aři", en= "to go up"},
{tf= "gəʕʕəđ", en= "to go up"},
{tf= "aři", en= "to climb"},
{tf= "hwa", en= "to go down"},
{tf= "đ’ā", en= "to go down"},
{tf= "ffəɣ", en= "to go out"},
{tf= "as", en= "to come"},
{tf= "đwəř", en= "to come back"},
{tf= "ā’žəʕ", en= "to come back"},
{tf= "ʕqəƀ", en= "to come back"},
{tf= "uyua", en= "to leave"},
{tf= "sməħ", en= "to leave"},
{tf= "xřa", en= "to leave"},
{tf= "wəd’d’ā", en= "to disappear"},
{tf= "ā’wəř", en= "to flee"},
{tf= "đ’fā", en= "to follow"},
{tf= "đ’fā", en= "to pursue"},
{tf= "awəđ’", en= "to arrive"},
{tf= "řəħħəg", en= "to arrive"},
{tf= "ađəs", en= "to approach"},
{tf= "qarrəƀ", en= "to approach"},
{tf= "ađəf", en= "to enter"},
{tf= "āggwəħ", en= "to go or return home"},
{tf= "çsi", en= "to carry"},
{tf= "awi", en= "to bring"},
{tf= "ssəkk", en= "to send"},
{tf= "gəwwəđ", en= "to lead"},
{tf= "ndəh", en= "to lead"},
{tf= "ndəh", en= "to drive"},
{tf= "ni", en= "to ride"},
{tf= "ʕān", en= "to push"},
{tf= "aƀriđ", en= "the road"},
{tf= "ŧaƀritt", en= "the path"},
{tf= "řqəndāŧ", en= "the bridge"},
{tf= "karru", en= "the cart or wagon"},
{tf= "ŧažarrat", en= "the wheel"},
{tf= "ɣiř", en= "the axle"},
{tf= "aɣar’r’aƀu", en= "the ship"},
{tf= "ŧaɣar’r’aƀut", en= "the boat"},
{tf= "fluka", en= "the boat"},
{tf= "imqəddəf", en= "the paddle"},
{tf= "qəddəf", en= "to row"},
{tf= "ƀul’anti", en= "the rudder"},
{tf= "řəqřəʕ", en= "the mast"},
{tf= "řƀaš n řəqřəʕ", en= "the sail"},
{tf= "ařiyzim", en= "the anchor"},
{tf= "řmuyyi", en= "the port"},
{tf= "arrimā", en= "to land"},
{tf= "ɣā", en= "to have"},
{tf= "çsi", en= "to take"},
{tf= "kkəs", en= "to take"},
{tf= "t’t’əf", en= "to grasp"},
{tf= "šəbbā", en= "to hold"},
{tf= "xəmməř", en= "to keep"},
{tf= "řħažəŧ", en= "the thing"},
{tf= "əwš", en= "to give"},
{tf= "arr", en= "to give back"},
{tf= "xəmməř", en= "to preserve"},
{tf= "sarrƀa", en= "to rescue"},
{tf= "āz’", en= "to destroy"},
{tf= "āddəž", en= "to destroy"},
{tf= "žāħ", en= "to injure"},
{tf= "ssəndəf", en= "to injure"},
{tf= "yzəm", en= "to injure"},
{tf= "đ’arr", en= "to damage"},
{tf= "fəttəš", en= "to look for"},
{tf= "āzu", en= "to look for"},
{tf= "af", en= "to find"},
{tf= "wəd’d’ā", en= "to lose"},
{tf= "đ’řəq", en= "to let go"},
{tf= "ā’xu", en= "to let go"},
{tf= "řəfřus", en= "the money"},
{tf= "ŧinʕašin", en= "the money"},
{tf= "ttmənyaŧ", en= "the money"},
{tf= "s’s’āf", en= "the coin"},
{tf= "təžžā", en= "rich"},
{tf= "řməskin", en= "poor"},
{tf= "aməz’řuđ’", en= "poor"},
{tf= "aməsʕi", en= "the beggar"},
{tf= "aqəzzaz", en= "stingy"},
{tf= "piyisa", en= "stingy"},
{tf= "āđ’əř", en= "to lend"},
{tf= "āđ’əř", en= "to borrow"},
{tf= "t’t’ās’", en= "to owe"},
{tf= "amā’was", en= "the debt"},
{tf= "xəǧǧəs’", en= "to pay"},
{tf= "řeħsaƀ", en= "the bill"},
{tf= "ddariƀa", en= "the tax"},
{tf= "šra", en= "to hire"},
{tf= "paɣa", en= "the wages"},
{tf= "řmunəŧ", en= "the wages"},
{tf= "səddā", en= "to earn"},
{tf= "āƀəħ", en= "to earn"},
{tf= "ħra", en= "to earn"},
{tf= "s’əɣ", en= "to buy"},
{tf= "ažžu", en= "to buy"},
{tf= "zzənz", en= "to sell"},
{tf= "sawəm", en= "to trade or barter"},
{tf= "at’ižari", en= "the merchant"},
{tf= "ssuq", en= "the market"},
{tf= "ŧħanətt", en= "the shop/store"},
{tf= "ttaman", en= "the price"},
{tf= "ɣřa", en= "expensive"},
{tf= "āxəs’", en= "cheap"},
{tf= "ƀđ’a", en= "to share"},
{tf= "wzən", en= "to weigh"},
{tf= "awān", en= "after"},
{tf= "awān", en= "behind"},
{tf= "đi", en= "in"},
{tf= "ɣā", en= "at"},
{tf= "t’t’āf", en= "beside"},
{tf= "s wadday", en= "down"},
{tf= "qƀəř", en= "before"},
{tf= "zzaŧ", en= "in front of"},
{tf= "đi", en= "inside"},
{tf= "ƀarra", en= "outside"},
{tf= "adu", en= "under"},
{tf= "ggw žənna", en= "up"},
{tf= "s nnəž", en= "above"},
{tf= "amšan", en= "the place"},
{tf= "ssās", en= "to put"},
{tf= "qqim", en= "to sit"},
{tf= "zzəř", en= "to lie down"},
{tf= "bbuzzəř", en= "to lie down"},
{tf= "ƀədd", en= "to stand"},
{tf= "qqim", en= "to remain"},
{tf= "ssmun", en= "to gather"},
{tf= "žməʕ", en= "to gather"},
{tf= "yāw", en= "to gather"},
{tf= "ħāwəš", en= "to pick up"},
{tf= "řqəđ’", en= "to pick up"},
{tf= "ssmun", en= "to join"},
{tf= "ssəřsəq", en= "to join"},
{tf= "ssməřqa", en= "to join"},
{tf= "fā’q", en= "to separate"},
{tf= "fs’əř", en= "to separate"},
{tf= "ƀđ’a", en= "to separate"},
{tf= "fāz", en= "to separate"},
{tf= "fān", en= "to separate"},
{tf= "ƀđ’a", en= "to divide"},
{tf= "āz’əm", en= "to open"},
{tf= "bəlləʕ", en= "to shut"},
{tf= "qqən", en= "to shut"},
{tf= "đəř", en= "to cover"},
{tf= "ssnuffā", en= "to hide"},
{tf= "aʕřa", en= "high"},
{tf= "ađā", en= "low"},
{tf= "ŧqiššit", en= "the top"},
{tf= "ŧisi", en= "the bottom"},
{tf= "anəggaru", en= "the end(1)"},
{tf= "qđ’əʕ", en= "pointed"},
{tf= "aɣəzđis", en= "the edge"},
{tf= "aɣəzđis", en= "the side"},
{tf= "řwəs’ŧ", en= "the middle"},
{tf= "afusi", en= "right(1)"},
{tf= "yəffus", en= "right(1)"},
{tf= "az’əřmađ’", en= "left"},
{tf= "z’əřməđ’", en= "left"},
{tf= "ađəs", en= "near"},
{tf= "ggwəž", en= "far"},
{tf= "ššāq", en= "the east"},
{tf= "řɣāƀ", en= "the west"},
{tf= "ššamal", en= "the north"},
{tf= "lžanuƀ", en= "the south"},
{tf= "ɣmi", en= "to grow"},
{tf= "ymi", en= "to grow"},
{tf= "mɣā", en= "to grow"},
{tf= "ggam", en= "to grow"},
{tf= "ʕƀā’", en= "to measure"},
{tf= "aməqqr’an", en= "big"},
{tf= "aməz’z’yan", en= "small"},
{tf= "aməʕnan", en= "small"},
{tf= "aziyrā", en= "long"},
{tf= "aziyrā", en= "tall"},
{tf= "aquđ’ađ’", en= "short"},
{tf= "miriw", en= "wide"},
{tf= "ħsā", en= "narrow"},
{tf= "gđā", en= "thick"},
{tf= "azđađ", en= "thin"},
{tf= "aǧǧəɣ", en= "deep"},
{tf= "aʕřa", en= "shallow"},
{tf= "aǧǧəɣ", en= "shallow"},
{tf= "wat’a", en= "flat"},
{tf= "nišan", en= "straight"},
{tf= "fā’ɣ", en= "crooked"},
{tf= "fāyəđ’", en= "crooked"},
{tf= "ŧas’ənnāŧ", en= "the hook"},
{tf= "ŧaɣmā’ŧ", en= "the corner"},
{tf= "kruši", en= "the cross"},
{tf= "muř’əbbəʕ", en= "the square"},
{tf= "aquřay", en= "round"},
{tf= "ŧaquřašŧ", en= "the circle"},
{tf= "ŧšamma", en= "the ball"},
{tf= "ƀalun", en= "the ball"},
{tf= "ašarriđ’", en= "the line"},
{tf= "ŧas’ettit", en= "the line"},
{tf= "aħfua", en= "the hole"},
{tf= "axƀuš", en= "the hole"},
{tf= "šaƀəh", en= "similar"},
{tf= "āwəs", en= "similar"},
{tf= "ƀəddəř", en= "to change"},
{tf= "ziru", en= "zero"},
{tf= "ižžən", en= "one"},
{tf= "ištən", en= "one"},
{tf= "ŧnayən", en= "two"},
{tf= "ŧřaŧa", en= "three"},
{tf= "āƀʕa", en= "four"},
{tf= "xəmsa", en= "five"},
{tf= "sətta", en= "six"},
{tf= "səƀʕa", en= "seven"},
{tf= "ŧmənya", en= "eight"},
{tf= "tsʕa", en= "nine"},
{tf= "ʕəšr’a", en= "ten"},
{tf= "ħiđ’ʕaš", en= "eleven"},
{tf= "ŧənʕaš’", en= "twelve"},
{tf= "xəmməzt’aš", en= "fifteen"},
{tf= "ʕišrin", en= "twenty"},
{tf= "mya", en= "a hundred"},
{tf= "ařəf", en= "a thousand"},
{tf= "t’awəz", en= "a thousand"},
{tf= "ħsəƀ", en= "to count"},
{tf= "marra", en= "all"},
{tf= "at’t’as", en= "many"},
{tf= "kŧā", en= "more"},
{tf= "mahu", en= "more"},
{tf= "đrus", en= "few"},
{tf= "xarrəbbi", en= "enough"},
{tf= "ša", en= "some"},
{tf= "ahim’uř", en= "the crowd"},
{tf= "ššua", en= "full"},
{tf= "ʕəmmā’", en= "full"},
{tf= "xwa", en= "empty"},
{tf= "awəzwiz", en= "the piece"},
{tf= "murs’u", en= "the piece"},
{tf= "azyən", en= "the half"},
{tf= "ɣia", en= "only"},
{tf= "waha", en= "only"},
{tf= "ħaša", en= "only"},
{tf= "wəħđ-", en= "alone"},
{tf= "aməzwaru", en= "first"},
{tf= "anəggaru", en= "last"},
{tf= "wis ŧnayen", en= "second"},
{tf= "ŧyuya", en= "the pair"},
{tf= "māŧayən", en= "twice/two times"},
{tf= "wis ŧřaŧa", en= "third"},
{tf= "ŧřaŧa", en= "three times"},
{tf= "řwəqŧ", en= "the time"},
{tf= "řqədd", en= "the age"},
{tf= "žžđiđ", en= "new"},
{tf= "aməz’z’yan", en= "young"},
{tf= "aməqqr’an", en= "old"},
{tf= "awəssā", en= "old"},
{tf= "ziš", en= "early"},
{tf= "řəxx=u", en= "now"},
{tf= "řəxx=u", en= "immediately"},
{tf= "đəɣya", en= "immediately"},
{tf= "s ŧazzřa", en= "immediately"},
{tf= "đəɣya", en= "fast"},
{tf= "s ŧazzřa", en= "fast"},
{tf= "šway šway", en= "slow"},
{tf= "qəǧǧəq", en= "to hurry"},
{tf= "ʕət’t’ā", en= "to be late"},
{tf= "ƀđa", en= "to begin"},
{tf= "kumasa", en= "to begin"},
{tf= "ssənti", en= "to begin"},
{tf= "ƀəddu", en= "the beginning"},
{tf= "kk", en= "to last"},
{tf= "anəggaru", en= "the end(2)"},
{tf= "kəmməř", en= "to finish"},
{tf= "ssƀədd", en= "to cease"},
{tf= "wžəđ", en= "ready"},
{tf= "řəƀđa", en= "always"},
{tf= "at’t’as", en= "often"},
{tf= "ša n marraŧ", en= "sometimes"},
{tf= "đəɣya", en= "soon"},
{tf= "at’t’as", en= "for a long time"},
{tf= "lmudda t taməqqrant", en= "for a long time"},
{tf= "ʕəmmās", en= "never"},
{tf= "ŧanya", en= "again"},
{tf= "ʕawəđ", en= "again"},
{tf= "nnhā", en= "the day(1)"},
{tf= "nhā", en= "the day(2)"},
{tf= "ǧǧiřəŧ", en= "the night"},
{tf= "řəfžā", en= "the dawn"},
{tf= "s’s’ƀəħ", en= "the morning"},
{tf= "azyən n nnhā", en= "the midday"},
{tf= "aʕəšši", en= "the afternoon"},
{tf= "ŧaməddiŧ", en= "the evening"},
{tf= "nnhar=a", en= "today"},
{tf= "ŧiwəšša", en= "tomorrow"},
{tf= "fāwišša", en= "the day after tomorrow"},
{tf= "iđ’ənnađ’", en= "yesterday"},
{tf= "fāyiđ’ənnađ’", en= "the day before yesterday"},
{tf= "ŧsaʕətt", en= "the hour"},
{tf= "ŧsaʕətt", en= "the clock"},
{tf= "simana", en= "the week"},
{tf= "řħədd", en= "Sunday"},
{tf= "řəŧnayən", en= "Monday"},
{tf= "ttřaŧa", en= "Tuesday"},
{tf= "řāƀʕa", en= "Wednesday"},
{tf= "řəxmis", en= "Thursday"},
{tf= "žžəmʕa", en= "Friday"},
{tf= "ssəfŧ", en= "Saturday"},
{tf= "ššhā", en= "the month"},
{tf= "asəggwas", en= "the year"},
{tf= "řməšŧa", en= "the winter"},
{tf= "arrƀiʕ", en= "the spring(2)"},
{tf= "řəxrif", en= "the summer"},
{tf= "anəƀđu", en= "the summer"},
{tf= "řəxrif", en= "the autumn/fall"},
{tf= "ttfuħ", en= "to smell(1)"},
{tf= "nəffəħ", en= "to sniff"},
{tf= "šəmm", en= "to smell(2)"},
{tf= "gg arriħŧ", en= "to smell(2)"},
{tf= "ttfuħ", en= "fragrant"},
{tf= "ās’uđ’", en= "stinking"},
{tf= "đyəs ttiƀəŧ", en= "to taste"},
{tf= "miz’iđ’", en= "sweet"},
{tf= "aməǧǧaħ", en= "salty"},
{tf= "amāz’ag", en= "bitter"},
{tf= "asəmmam", en= "sour"},
{tf= "aman iƀā’wən", en= "brackish"},
{tf= "səř", en= "to hear"},
{tf= "ssħəss", en= "to listen"},
{tf= "řħəss", en= "the sound or noise"},
{tf= "žhəđ", en= "loud"},
{tf= "ssqā", en= "quiet"},
{tf= "t’t’rankiř", en= "quiet"},
{tf= "wařa", en= "to see"},
{tf= "z’ā", en= "to see"},
{tf= "xzā", en= "to look"},
{tf= "ssšən", en= "to show"},
{tf= "āɣ", en= "to shine"},
{tf= "ttissiq", en= "to shine"},
{tf= "kulur", en= "the colour/color"},
{tf= "fsəs", en= "light(2)"},
{tf= "ħđ’əq", en= "dark"},
{tf= "ašəmřař", en= "white"},
{tf= "aƀāršan", en= "black"},
{tf= "azəggwaɣ", en= "red"},
{tf= "aziyza", en= "blue"},
{tf= "aziyza", en= "green"},
{tf= "arrƀiʕi", en= "green"},
{tf= "awr’aɣ", en= "yellow"},
{tf= "ħađa", en= "to touch"},
{tf= "šwi", en= "to pinch"},
{tf= "aša", en= "to feel"},
{tf= "qsəħ", en= "hard"},
{tf= "āđ’əƀ", en= "soft"},
{tf= "aħā’šaw", en= "rough(1)"},
{tf= "ařəqqaɣ", en= "smooth"},
{tf= "qđ’əʕ", en= "sharp"},
{tf= "ħfa", en= "blunt"},
{tf= "đqəř", en= "heavy"},
{tf= "fsəs", en= "light(1)"},
{tf= "uff", en= "wet"},
{tf= "azəɣ", en= "dry"},
{tf= "āɣ", en= "hot"},
{tf= "ħma", en= "warm"},
{tf= "asəmmađ’", en= "cold"},
{tf= "aməzđag", en= "clean"},
{tf= "wəssəx", en= "dirty"},
{tf= "marrəɣ", en= "dirty"},
{tf= "ššəƀřəq", en= "wrinkled"},
{tf= "arruħ", en= "the soul or spirit"},
{tf= "ttəƀhəŧ", en= "surprised or astonished"},
{tf= "šwarti", en= "the good luck"},
{tf= "ssəʕđ", en= "the good luck"},
{tf= "fāħ", en= "happy"},
{tf= "đ’ħəš", en= "to laugh"},
{tf= "ssfianən", en= "to smile"},
{tf= "irā", en= "to play"},
{tf= "əxs", en= "to love"},
{tf= "ssuđəm", en= "to kiss"},
{tf= "đarrəʕ", en= "to embrace"},
{tf= "řəħriq", en= "the pain"},
{tf= "ħzən", en= "the grief"},
{tf= "amnus", en= "the anxiety"},
{tf= "ndəm", en= "to regret or be sorry"},
{tf= "zziǧǧəz", en= "the pity"},
{tf= "ru", en= "to cry"},
{tf= "amət’t’a", en= "the tear"},
{tf= "šā’h", en= "to hate"},
{tf= "žžnun", en= "the anger"},
{tf= "marrɣa", en= "the anger"},
{tf= "ŧismin", en= "the envy or jealousy"},
{tf= "řəħsađ", en= "the envy or jealousy"},
{tf= "ɣarr", en= "the envy or jealousy"},
{tf= "asəđħi", en= "the shame"},
{tf= "šnəʕ", en= "proud"},
{tf= "zʕəm", en= "to dare"},
{tf= "azəʕʕam", en= "brave"},
{tf= "ŧiggwđi", en= "the fear"},
{tf= "lxat’ař", en= "the danger"},
{tf= "əxs", en= "to want"},
{tf= "āzu", en= "to want"},
{tf= "ixđ’ā", en= "to choose"},
{tf= "ssiŧəm", en= "to hope"},
{tf= "ttmənna", en= "to hope"},
{tf= "s’s’əħħ", en= "true"},
{tf= "ŧiđətt", en= "true"},
{tf= "ssxar’r’əq", en= "to lie(2)"},
{tf= "aɣar’r’i", en= "the deceit"},
{tf= "ʕfu", en= "to forgive"},
{tf= "sməħ", en= "to forgive"},
{tf= "šən", en= "good"},
{tf= "s’ƀəħ", en= "good"},
{tf= "aʕəffan", en= "bad"},
{tf= "wā yəħři", en= "bad"},
{tf= "nišan", en= "right(2)"},
{tf= "ɣalat’", en= "wrong"},
{tf= "falta", en= "the fault"},
{tf= "ƀuqqā", en= "the fault"},
{tf= "ɣřəđ’", en= "the fault"},
{tf= "ɣlət’", en= "the fault"},
{tf= "falta", en= "the mistake"},
{tf= "đ’řəm", en= "the blame"},
{tf= "šəkkā", en= "the praise"},
{tf= "s’ƀəħ", en= "beautiful"},
{tf= "šən", en= "beautiful"},
{tf= "šəwwā", en= "beautiful"},
{tf= "aʕəffan", en= "ugly"},
{tf= "wā yəħři", en= "ugly"},
{tf= "řəmməz’", en= "greedy"},
{tf= "miɣis", en= "clever"},
{tf= "ŧiɣiŧ", en= "clever"},
{tf= "řƀař", en= "the mind"},
{tf= "řəʕqəř", en= "the mind"},
{tf= "xəmməm", en= "to think(1)"},
{tf= "pins’ā", en= "to think(1)"},
{tf= "xarrəs", en= "to think(1)"},
{tf= "tɣiř", en= "to think(2)"},
{tf= "amən", en= "to believe"},
{tf= "tiqq", en= "to believe"},
{tf= "fhəm", en= "to understand"},
{tf= "ssən", en= "to know"},
{tf= "kašəf", en= "to guess"},
{tf= "ʕəyyəƀ", en= "to imitate"},
{tf= "tƀan", en= "to seem"},
{tf= "lfikra", en= "the idea"},
{tf= "řəʕqəř", en= "wise"},
{tf= "aqəffuħ", en= "stupid"},
{tf= "aƀuhaři", en= "mad"},
{tf= "řməđ", en= "to learn"},
{tf= "ħfəđ’", en= "to learn"},
{tf= "ɣā", en= "to study"},
{tf= "ssɣā", en= "to teach"},
{tf= "ssəřməđ", en= "to teach"},
{tf= "aməħđ’ā", en= "the pupil"},
{tf= "lmuʕəllim", en= "the teacher"},
{tf= "ŧamziyđa", en= "the school"},
{tf= "lmədras’a", en= "the school"},
{tf= "ssəkwila", en= "the school"},
{tf= "ʕqəř", en= "to remember"},
{tf= "ttu", en= "to forget"},
{tf= "fāz", en= "clear"},
{tf= "siɣur’u", en= "certain"},
{tf= "ulaƀudd", en= "certain"},
{tf= "ssəfhəm", en= "to explain"},
{tf= "šarrəħ", en= "to explain"},
{tf= "řɣar’ađ", en= "the intention"},
{tf= "řəsƀaƀ", en= "the cause"},
{tf= "ššəkk", en= "the doubt"},
{tf= "tahəm", en= "to suspect"},
{tf= "ɣđā", en= "to betray"},
{tf= "ħđaž", en= "the need or necessity"},
{tf= "hwən", en= "easy"},
{tf= "qsəħ", en= "difficult"},
{tf= "wʕā’", en= "difficult"},
{tf= "pr’uƀā", en= "to try"},
{tf= "qəǧǧəƀ", en= "to try"},
{tf= "ʕayā", en= "to try"},
{tf= "t’t’ariqa", en= "the manner"},
{tf= "đ", en= "and"},
{tf= "u", en= "and"},
{tf= "puř’ki", en= "because"},
{tf= "s minzi", en= "because"},
{tf= "l’axat’ā", en= "because"},
{tf= "mařa", en= "if"},
{tf= "niɣ", en= "or"},
{tf= "wah", en= "yes"},
{tf= "lla", en= "no"},
{tf= "maməš", en= "how?"},
{tf= "məšħař", en= "how many?"},
{tf= "məšħař", en= "how much?"},
{tf= "min", en= "what?"},
{tf= "məřmi", en= "when?"},
{tf= "mani", en= "where?"},
{tf= "man", en= "which?"},
{tf= "wi", en= "who?"},
{tf= "mayəmmi", en= "why?"},
{tf= "maɣā", en= "why?"},
{tf= "ŧmižža", en= "the voice"},
{tf= "s’s’ut", en= "the voice"},
{tf= "ɣənnəž", en= "to sing"},
{tf= "ssɣuyy", en= "to shout"},
{tf= "žəʕžəʕ", en= "to shout"},
{tf= "təmtəm", en= "to whisper"},
{tf= "s’əffā", en= "to whistle"},
{tf= "ssɣuyy", en= "to shriek"},
{tf= "ssɣuyy", en= "to howl"},
{tf= "ssiwəř", en= "to speak or talk"},
{tf= "nnəɣnəɣ", en= "to stutter or stammer"},
{tf= "ini", en= "to say"},
{tf= "ʕawəđ", en= "to tell"},
{tf= "lxut’ƀa", en= "the speech"},
{tf= "ssqā", en= "to be silent"},
{tf= "awař", en= "the language"},
{tf= "lluɣa", en= "the language"},
{tf= "awař", en= "the word"},
{tf= "isəm", en= "the name"},
{tf= "ssəqsa", en= "to ask(1)"},
{tf= "arr", en= "to answer"},
{tf= "wažəƀ", en= "to answer"},
{tf= "nʕəm", en= "to admit"},
{tf= "nkā", en= "to deny"},
{tf= "ttā", en= "to ask(2)"},
{tf= "ʕahəđ", en= "to promise"},
{tf= "agi", en= "to refuse"},
{tf= "ħar’r’əm", en= "to forbid"},
{tf= "řaɣa", en= "to call(1)"},
{tf= "səmma", en= "to call(2)"},
{tf= "ƀarrəħ", en= "to announce"},
{tf= "hudd", en= "to threaten"},
{tf= "gānəz", en= "to boast"},
{tf= "ari", en= "to write"},
{tf= "ɣā", en= "to read"},
{tf= "řšiɣəđ’", en= "the paper"},
{tf= "ŧawr’iqŧ", en= "the paper"},
{tf= "stilu", en= "the pen"},
{tf= "lappis", en= "the pen"},
{tf= "lkitaƀ", en= "the book"},
{tf= "ššaʕiř", en= "the poet"},
{tf= "aməđyaz", en= "the poet"},
{tf= "ŧamža", en= "the flute"},
{tf= "dəřbuga", en= "the drum"},
{tf= "t’t’ƀəř", en= "the drum"},
{tf= "t’amt’am", en= "the drum"},
{tf= "ƀuwaššawən", en= "the horn or trumpet"},
{tf= "ŧammua’ŧ", en= "the country"},
{tf= "ŧandint", en= "the town"},
{tf= "ddšā’", en= "the village"},
{tf= "řħədd", en= "the boundary"},
{tf= "iwđan", en= "the people"},
{tf= "ŧāfiqŧ", en= "the clan"},
{tf= "amɣā", en= "the chieftain"},
{tf= "aʕəkkaz", en= "the walking stick"},
{tf= "ŧaɣɣašŧ", en= "the walking stick"},
{tf= "ħkəm", en= "to rule or govern"},
{tf= "đ’əbbā", en= "to rule or govern"},
{tf= "ažəǧǧiđ", en= "the king"},
{tf= "lmalik", en= "the king"},
{tf= "ŧažəǧǧitt", en= "the queen"},
{tf= "lmalika", en= "the queen"},
{tf= "lmuwat’in", en= "the citizen"},
{tf= "siđi", en= "the master"},
{tf= "isməɣ", en= "the slave"},
{tf= "ŧayya", en= "the slave"},
{tf= "axəddam", en= "the servant"},
{tf= "aħur’r’i", en= "the freeman"},
{tf= "đ’řəq", en= "to liberate"},
{tf= "ā’xu", en= "to liberate"},
{tf= "amā’", en= "to command or order"},
{tf= "gg array", en= "to obey"},
{tf= "səlləm", en= "to permit"},
{tf= "aməddukəř", en= "the friend"},
{tf= "řəʕđu", en= "the enemy"},
{tf= "ažžā’", en= "the neighbour"},
{tf= "aƀarrani", en= "the stranger"},
{tf= "anəwži", en= "the guest"},
{tf= "ʕāđ‘", en= "to invite"},
{tf= "ʕawən", en= "to help"},
{tf= "mnəʕ", en= "to prevent"},
{tf= "ssənžəm", en= "to prevent"},
{tf= "lʕađa", en= "the custom"},
{tf= "amənɣi", en= "the quarrel"},
{tf= "ŧaməʕmuč", en= "the plot"},
{tf= "msəřqa", en= "to meet"},
{tf= "mməřqa", en= "to meet"},
{tf= "ŧaqəħƀəšŧ", en= "the prostitute"},
{tf= "řqəħƀa", en= "the prostitute"},
{tf= "mmnəɣ", en= "to fight"},
{tf= "řħāƀ", en= "the war or battle"},
{tf= "garra", en= "the war or battle"},
{tf= "ssalam", en= "the peace"},
{tf= "řʕəskā", en= "the army"},
{tf= "amxazni", en= "the soldier"},
{tf= "aʕəskari", en= "the soldier"},
{tf= "řəsnaħ", en= "the weapons"},
{tf= "ddəbbuz", en= "the club"},
{tf= "řqəws", en= "the bow"},
{tf= "ŧiššəwŧ", en= "the arrow"},
{tf= "lansa", en= "the spear"},
{tf= "ssif", en= "the sword"},
{tf= "ŧazwišŧ", en= "the gun"},
{tf= "aziđan", en= "the gun"},
{tf= "řəkřat’a", en= "the gun"},
{tf= "afuši", en= "the gun"},
{tf= "kasku", en= "the helmet"},
{tf= "uzzař", en= "the shield"},
{tf= "ŧaqsəfŧ", en= "the fortress"},
{tf= "lʕimara ?", en= "the tower"},
{tf= "arrƀəħ", en= "the victory"},
{tf= "ŧaxəs’s’āŧ", en= "the defeat"},
{tf= "hžəm", en= "the attack"},
{tf= "ħāš", en= "the attack"},
{tf= "ddafəʕ", en= "to defend"},
{tf= "ā’wəř", en= "to retreat"},
{tf= "twasləm", en= "to surrender"},
{tf= "anəħƀus", en= "the captive or prisoner"},
{tf= "aʕəssas", en= "the guard"},
{tf= "anday", en= "the ambush"},
{tf= "aƀəħri", en= "the fisherman"},
{tf= "ŧas’ənnāŧ", en= "the fishhook"},
{tf= "pilun", en= "the fishing line"},
{tf= "ŧrašša", en= "the fishnet"},
{tf= "ymā", en= "to hunt"},
{tf= "wwəŧ s uqāt’as’", en= "to shoot"},
{tf= "xđ’ā", en= "to miss"},
{tf= "ŧaxšəfŧ", en= "the trap"},
{tf= "řfəxx", en= "the trap"},
{tf= "ndi", en= "to trap"},
{tf= "řqanun", en= "the law"},
{tf= "řməħkama", en= "the court"},
{tf= "ħkəm", en= "to adjudicate"},
{tf= "řəħkam", en= "the judgment"},
{tf= "řqađ’i", en= "the judge"},
{tf= "wənni ittəđʕan", en= "the plaintiff"},
{tf= "wənni istəđʕan", en= "the defendant"},
{tf= "ššahəđ", en= "the witness"},
{tf= "žžaǧǧ", en= "to swear"},
{tf= "ŧžaǧǧiŧ", en= "the oath"},
{tf= "gg imi đi ...", en= "to accuse"},
{tf= "ħkəm", en= "to condemn"},
{tf= "ā’xu", en= "to acquit"},
{tf= "đ’řəq", en= "to acquit"},
{tf= "lʕiqaƀ", en= "the penalty or punishment"},
{tf= "mult’a", en= "the fine"},
{tf= "aƀrus’s’i", en= "the fine"},
{tf= "řəħƀəs", en= "the prison"},
{tf= "ŧamənɣawŧ", en= "the murder"},
{tf= "zzina", en= "the adultery"},
{tf= "řəfʕəř", en= "the rape"},
{tf= "ašā", en= "to steal"},
{tf= "axəwwan", en= "the thief"},
{tf= "ašəffā’", en= "the thief"},
{tf= "ddin", en= "the religion"},
{tf= "siđi ā’bbi", en= "the god"},
{tf= "l’l’ah", en= "the god"},
{tf= "lkanisa", en= "the church"},
{tf= "ŧamziyđa", en= "the church"},
{tf= "glisiya", en= "the church"},
{tf= "ŧamziyđa", en= "the mosque"},
{tf= "ŧɣās’ŧ", en= "the sacrifice"},
{tf= "ʕƀəđ", en= "to worship"},
{tf= "z’z’aǧǧ", en= "to pray"},
{tf= "lfaqi", en= "the priest"},
{tf= "qəddəs", en= "holy"},
{tf= "ħəddəŧ", en= "to preach"},
{tf= "xt’əƀ", en= "to preach"},
{tf= "ƀāk", en= "to bless"},
{tf= "nʕəř", en= "to curse"},
{tf= "z’um", en= "to fast"},
{tf= "lžənnəŧ", en= "the heaven"},
{tf= "žahannama", en= "the hell"},
{tf= "ʕifrit", en= "the demon"},
{tf= "lʔas’nam", en= "the idol"},
{tf= "ssħua", en= "the magic"},
{tf= "asəħħā", en= "the sorcerer or witch"},
{tf= "lʕaqisa", en= "the sorcerer or witch"},
{tf= "žžənn", en= "the ghost"},
{tf= "ʕifrit", en= "the ghost"},
{tf= "lʕalama", en= "the omen"},
{tf= "iməxŧan", en= "the circumcision"},
{tf= "arrađ’yu", en= "the radio"},
{tf= "ttiliƀizyun", en= "the television"},
{tf= "ttilifun", en= "the telephone"},
{tf= "bašklit", en= "the bicycle"},
{tf= "muƀila", en= "the motorcycle"},
{tf= "quči", en= "the car"},
{tf= "t’t’umuƀin", en= "the car"},
{tf= "t’t’uƀis", en= "the bus"},
{tf= "lkař", en= "the bus"},
{tf= "mašina", en= "the train"},
{tf= "t’t’iyara", en= "the airplane"},
{tf= "trisinti", en= "the electricity"},
{tf= "kwarinti", en= "the electricity"},
{tf= "ŧaz’ruŧ", en= "the battery"},
{tf= "fřina", en= "to brake"},
{tf= "mut’ua", en= "the motor"},
{tf= "mašina", en= "the machine"},
{tf= "lpitrul", en= "the petroleum"},
{tf= "s’pit’ā", en= "the hospital"},
{tf= "ŧaxəddant n s’pit’ā", en= "the nurse"},
{tf= "řəknina", en= "the pill or tablet"},
{tf= "pas’t’iya", en= "the pill or tablet"},
{tf= "ŧisiynəfŧ", en= "the injection"},
{tf= "nnwađ’ā", en= "the spectacles/glasses"},
{tf= "lməxzən", en= "the government"},
{tf= "arrayəs", en= "the president"},
{tf= "řwazia", en= "the minister"},
{tf= "lwaziř", en= "the minister"},
{tf= "pulisiya", en= "the police"},
{tf= "piřmi", en= "the driver's license"},
{tf= "matrikula", en= "the license plate"},
{tf= "lizđiyaŧ", en= "the birth certificate"},
{tf= "lžarima", en= "the crime"},
{tf= "lintixaƀ", en= "the election"},
{tf= "landris", en= "the address"},
{tf= "nnumr’u", en= "the number"},
{tf= "zzənqəŧ", en= "the street"},
{tf= "ŧaƀrat", en= "the post/mail"},
{tf= "siyyu", en= "the postage stamp"},
{tf= "tambā", en= "the postage stamp"},
{tf= "ŧaƀrat", en= "the letter"},
{tf= "kartpustal", en= "the postcard"},
{tf= "řbanku", en= "the bank"},
{tf= "ŧasəbbač", en= "the tap/faucet"},
{tf= "llaƀaƀu", en= "the sink"},
{tf= "bitəlma", en= "the toilet"},
{tf= "payas", en= "the mattress"},
{tf= "ŧaqədduħŧ", en= "the tin/can"},
{tf= "ƀulun", en= "the screw"},
{tf= "t’urnifis", en= "the screwdriver"},
{tf= "ŧazəyyat", en= "the bottle"},
{tf= "ħalawit", en= "the candy/sweets"},
{tf= "plastik", en= "the plastic"},
{tf= "řƀumba", en= "the bomb"},
{tf= "ŧħanətt", en= "the workshop"},
{tf= "garru", en= "the cigarette"},
{tf= "lžariđa", en= "the newspaper"},
{tf= "žžuanal", en= "the newspaper"},
{tf= "llumiya", en= "the calendar"},
{tf= "lfiləm", en= "the film/movie"},
{tf= "pirikula", en= "the film/movie"},
{tf= "muziqa", en= "the music"},
{tf= "aɣənniž", en= "the song"},
{tf= "ddisku", en= "the song"},
{tf= "atay", en= "the tea"},
{tf= "řqəhwa", en= "the coffee"},
{tf= "iři", en= "to be"},
{tf= "đwəř", en= "to become"},
{tf= "đħa", en= "to become"},
{tf= "ƀřa", en= "without"},
{tf= "akəđ", en= "with"},
{tf= "đi", en= "through"},
{tf= "wā", en= "not"},
{tf= "wa", en= "this"},
{tf= "win", en= "that"},
{tf= "wənni", en= "that"},
{tf= "đa", en= "here"},
{tf= "đin", en= "there"},
{tf= "nnəɣni", en= "other"},
{tf= "wənni d yusin", en= "next"},
{tf= "walu", en= "nothing"}}
